name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The repository has been cloned to the runner."
      - run: ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
